### ISSUE TITLE
[v 1.21] ERROR TypeError: p.default is not a function 

### ISSUE THREAD

**Issue by ToufMar** [Rebilly/ReDoc#434]
Hello, 
I have a problem with the new version 1.21. 
When i worked on the 1.19 everything was ok but now, when i try to use my own minified file "redoc.min.js" i have this error on the console and my page does not run: 

>core.es5.js:1020 
ERROR TypeError: p.default is not a function
    at e.getTagsItems (menu.service.ts:393)
    at e.buildMenu (menu.service.ts:453)
    at t._next (menu.service.ts:72)
    at t.__tryOrSetError (Subscriber.js:247)
    at t.next (Subscriber.js:187)
    at t._next (Subscriber.js:125)
    at t.next (Subscriber.js:89)
    at t._subscribe (BehaviorSubject.js:28)
    at t.e._trySubscribe (Observable.js:172)
    at t._trySubscribe (Subject.js:97)
_ @ core.es5.js:1020
e.handleError @ core.es5.js:1080
t.handleError @ custom-error-handler.ts:11
(anonymous) @ core.es5.js:4819
e.invoke @ zone.js:392
r.run @ zone.js:142
e.runOutsideAngular @ core.es5.js:3844
t.tick @ core.es5.js:4819
(anonymous) @ core.es5.js:4684
e.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
e.invoke @ zone.js:391
r.run @ zone.js:142
e.run @ core.es5.js:3821
next @ core.es5.js:4684
t.object.o @ core.es5.js:3635
t.__tryOrUnsub @ Subscriber.js:238
t.next @ Subscriber.js:185
t._next @ Subscriber.js:125
t.next @ Subscriber.js:89
t.next @ Subject.js:55
t.emit @ core.es5.js:3621
oe @ core.es5.js:3855
onHasTask @ core.es5.js:3903
e.hasTask @ zone.js:445
e._updateTaskCount @ zone.js:465
r._updateTaskCount @ zone.js:289
r.runTask @ zone.js:209
o @ zone.js:602
t.invokeTask @ zone.js:503
i.isUsingGlobalCallback.invoke @ zone.js:488
n @ zone.js:2040
setTimeout (async)
o @ zone.js:2056
e.scheduleTask @ zone.js:411
onScheduleTask @ zone.js:301
e.scheduleTask @ zone.js:405
r.scheduleTask @ zone.js:236
r.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2072
o.(anonymous function) @ zone.js:1366
o @ browser.js:41
d.nextTick @ browser.js:143
n @ index.js:26
x @ _stream_readable.js:776
l.resume @ _stream_readable.js:768
l.on @ _stream_readable.js:738
(anonymous) @ http.js:169
n @ events.js:165
n.emit @ events.js:81
h._connect @ request.js:247
(anonymous) @ request.js:140
e.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
e.invoke @ zone.js:391
r.run @ zone.js:142
(anonymous) @ zone.js:873
e.invokeTask @ zone.js:425
onInvokeTask @ core.es5.js:3881
e.invokeTask @ zone.js:424
r.runTask @ zone.js:192
o @ zone.js:602
Promise.then (async)
r @ zone.js:585
e.scheduleTask @ zone.js:414
onScheduleTask @ zone.js:301
e.scheduleTask @ zone.js:405
r.scheduleTask @ zone.js:236
r.scheduleMicroTask @ zone.js:256
c @ zone.js:871
l @ zone.js:819
(anonymous) @ zone.js:746
Promise.then (async)
(anonymous) @ zone.js:1049
e @ zone.js:890
e.then @ zone.js:1048
h._onFinish @ request.js:138
(anonymous) @ request.js:62
n.emit @ events.js:78
C @ _stream_writable.js:607
S @ _stream_writable.js:615
u.end @ _stream_writable.js:571
h.end @ request.js:275
s.get @ index.js:43
(anonymous) @ http.js:147
e @ zone.js:890
i @ http.js:143
(anonymous) @ http.js:104
e @ zone.js:890
o @ http.js:99
read @ http.js:84
r @ plugins.js:138
c @ plugins.js:81
(anonymous) @ plugins.js:70
e @ zone.js:890
t.run @ plugins.js:69
(anonymous) @ parse.js:74
e @ zone.js:890
o @ parse.js:65
r @ parse.js:37
r.parse @ index.js:101
r.resolve @ index.js:154
r.bundle @ index.js:196
(anonymous) @ spec-manager.ts:47
e @ zone.js:890
e.load @ spec-manager.ts:45
t.load @ redoc.ts:114
t.ngOnInit @ redoc.ts:155
xn @ core.es5.js:10843
dr @ core.es5.js:12341
cr @ core.es5.js:12284
Fr @ core.es5.js:12974
(anonymous) @ redoc.ngfactory.ts:181
updateDirectives @ core.es5.js:12718
ur @ core.es5.js:12251
e.detectChanges @ core.es5.js:10174
(anonymous) @ core.es5.js:4812
t.tick @ core.es5.js:4812
t._loadComponent @ core.es5.js:4787
t.bootstrap @ core.es5.js:4775
(anonymous) @ core.es5.js:4546
t._moduleDoBootstrap @ core.es5.js:4546
(anonymous) @ core.es5.js:4508
e.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
e.invoke @ zone.js:391
r.run @ zone.js:142
(anonymous) @ zone.js:873
e.invokeTask @ zone.js:425
onInvokeTask @ core.es5.js:3881
e.invokeTask @ zone.js:424
r.runTask @ zone.js:192
o @ zone.js:602
Promise.then (async)
r @ zone.js:585
e.scheduleTask @ zone.js:414
onScheduleTask @ zone.js:301
e.scheduleTask @ zone.js:405
r.scheduleTask @ zone.js:236
r.scheduleMicroTask @ zone.js:256
c @ zone.js:871
e.then @ zone.js:981
e.runInitializers @ core.es5.js:2813
(anonymous) @ core.es5.js:4506
me @ core.es5.js:4406
(anonymous) @ core.es5.js:4504
e.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
e.invoke @ zone.js:391
r.run @ zone.js:142
e.run @ core.es5.js:3821
t._bootstrapModuleFactoryWithZone @ core.es5.js:4495
t.bootstrapModuleFactory @ core.es5.js:4477
r @ bootstrap.ts:8
r @ index.ts:34
(anonymous) @ index.ts:56
(anonymous) @ index.ts:51
t @ bootstrap 44182149e1d7fb538521:19
(anonymous) @ redoc.min.js:47301
t @ bootstrap 44182149e1d7fb538521:19
(anonymous) @ bootstrap 44182149e1d7fb538521:62
(anonymous) @ bootstrap 44182149e1d7fb538521:62
(anonymous) @ universalModuleDefinition:9
(anonymous) @ universalModuleDefinition:9
core.es5.js:1020 ERROR Error: Uncaught (in promise): TypeError: p.default is not a function
TypeError: p.default is not a function
    at e.getTagsItems (menu.service.ts:393)
    at e.buildMenu (menu.service.ts:453)
    at t._next (menu.service.ts:72)
    at t.__tryOrSetError (Subscriber.js:247)
    at t.next (Subscriber.js:187)
    at t._next (Subscriber.js:125)
    at t.next (Subscriber.js:89)
    at t._subscribe (BehaviorSubject.js:28)
    at t.e._trySubscribe (Observable.js:172)
    at t._trySubscribe (Subject.js:97)
    at e.getTagsItems (menu.service.ts:393)
    at e.buildMenu (menu.service.ts:453)
    at t._next (menu.service.ts:72)
    at t.__tryOrSetError (Subscriber.js:247)
    at t.next (Subscriber.js:187)
    at t._next (Subscriber.js:125)
    at t.next (Subscriber.js:89)
    at t._subscribe (BehaviorSubject.js:28)
    at t.e._trySubscribe (Observable.js:172)
    at t._trySubscribe (Subject.js:97)
    at l (zone.js:824)
    at zone.js:876
    at e.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.es5.js:3881)
    at e.invokeTask (zone.js:424)
    at r.runTask (zone.js:192)
    at o (zone.js:602)
    at t.invokeTask (zone.js:503)
    at i.isUsingGlobalCallback.invoke (zone.js:488)
    at n (zone.js:2040)
_ @ core.es5.js:1020
e.handleError @ core.es5.js:1080
t.handleError @ custom-error-handler.ts:11
next @ core.es5.js:4503
t.object.o @ core.es5.js:3635
t.__tryOrUnsub @ Subscriber.js:238
t.next @ Subscriber.js:185
t._next @ Subscriber.js:125
t.next @ Subscriber.js:89
t.next @ Subject.js:55
t.emit @ core.es5.js:3621
(anonymous) @ core.es5.js:3912
e.invoke @ zone.js:392
r.run @ zone.js:142
e.runOutsideAngular @ core.es5.js:3844
onHandleError @ core.es5.js:3912
e.handleError @ zone.js:396
r.runGuarded @ zone.js:158
(anonymous) @ zone.js:702
n.microtaskDrainDone @ zone.js:707
o @ zone.js:610
t.invokeTask @ zone.js:503
i.isUsingGlobalCallback.invoke @ zone.js:488
n @ zone.js:2040
setTimeout (async)
o @ zone.js:2056
e.scheduleTask @ zone.js:411
onScheduleTask @ zone.js:301
e.scheduleTask @ zone.js:405
r.scheduleTask @ zone.js:236
r.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2072
o.(anonymous function) @ zone.js:1366
o @ browser.js:41
d.nextTick @ browser.js:143
n @ index.js:26
x @ _stream_readable.js:776
l.resume @ _stream_readable.js:768
l.on @ _stream_readable.js:738
(anonymous) @ http.js:169
n @ events.js:165
n.emit @ events.js:81
h._connect @ request.js:247
(anonymous) @ request.js:140
e.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
e.invoke @ zone.js:391
r.run @ zone.js:142
(anonymous) @ zone.js:873
e.invokeTask @ zone.js:425
onInvokeTask @ core.es5.js:3881
e.invokeTask @ zone.js:424
r.runTask @ zone.js:192
o @ zone.js:602
Promise.then (async)
r @ zone.js:585
e.scheduleTask @ zone.js:414
onScheduleTask @ zone.js:301
e.scheduleTask @ zone.js:405
r.scheduleTask @ zone.js:236
r.scheduleMicroTask @ zone.js:256
c @ zone.js:871
l @ zone.js:819
(anonymous) @ zone.js:746
Promise.then (async)
(anonymous) @ zone.js:1049
e @ zone.js:890
e.then @ zone.js:1048
h._onFinish @ request.js:138
(anonymous) @ request.js:62
n.emit @ events.js:78
C @ _stream_writable.js:607
S @ _stream_writable.js:615
u.end @ _stream_writable.js:571
h.end @ request.js:275
s.get @ index.js:43
(anonymous) @ http.js:147
e @ zone.js:890
i @ http.js:143
(anonymous) @ http.js:104
e @ zone.js:890
o @ http.js:99
read @ http.js:84
r @ plugins.js:138
c @ plugins.js:81
(anonymous) @ plugins.js:70
e @ zone.js:890
t.run @ plugins.js:69
(anonymous) @ parse.js:74
e @ zone.js:890
o @ parse.js:65
r @ parse.js:37
r.parse @ index.js:101
r.resolve @ index.js:154
r.bundle @ index.js:196
(anonymous) @ spec-manager.ts:47
e @ zone.js:890
e.load @ spec-manager.ts:45
t.load @ redoc.ts:114
t.ngOnInit @ redoc.ts:155
xn @ core.es5.js:10843
dr @ core.es5.js:12341
cr @ core.es5.js:12284
Fr @ core.es5.js:12974
(anonymous) @ redoc.ngfactory.ts:181
updateDirectives @ core.es5.js:12718
ur @ core.es5.js:12251
e.detectChanges @ core.es5.js:10174
(anonymous) @ core.es5.js:4812
t.tick @ core.es5.js:4812
t._loadComponent @ core.es5.js:4787
t.bootstrap @ core.es5.js:4775
(anonymous) @ core.es5.js:4546
t._moduleDoBootstrap @ core.es5.js:4546
(anonymous) @ core.es5.js:4508
e.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
e.invoke @ zone.js:391
r.run @ zone.js:142
(anonymous) @ zone.js:873
e.invokeTask @ zone.js:425
onInvokeTask @ core.es5.js:3881
e.invokeTask @ zone.js:424
r.runTask @ zone.js:192
o @ zone.js:602
Promise.then (async)
r @ zone.js:585
e.scheduleTask @ zone.js:414
onScheduleTask @ zone.js:301
e.scheduleTask @ zone.js:405
r.scheduleTask @ zone.js:236
r.scheduleMicroTask @ zone.js:256
c @ zone.js:871
e.then @ zone.js:981
e.runInitializers @ core.es5.js:2813
(anonymous) @ core.es5.js:4506
me @ core.es5.js:4406
(anonymous) @ core.es5.js:4504
e.invoke @ zone.js:392
onInvoke @ core.es5.js:3890
e.invoke @ zone.js:391
r.run @ zone.js:142
e.run @ core.es5.js:3821
t._bootstrapModuleFactoryWithZone @ core.es5.js:4495
t.bootstrapModuleFactory @ core.es5.js:4477
r @ bootstrap.ts:8
r @ index.ts:34
(anonymous) @ index.ts:56
(anonymous) @ index.ts:51
t @ bootstrap 44182149e1d7fb538521:19
(anonymous) @ redoc.min.js:47301
t @ bootstrap 44182149e1d7fb538521:19
(anonymous) @ bootstrap 44182149e1d7fb538521:62
(anonymous) @ bootstrap 44182149e1d7fb538521:62
(anonymous) @ universalModuleDefinition:9
(anonymous) @ universalModuleDefinition:9

I used "npm run build:prod" to minify my file to deploy in prod. Is it the good usage or did i do something wrong?

Thx, ToufMar :) .

**Comment by RomanGotsiy** [comment]
sorry for late reply... I somehow missed your issue 😞

Could you please share your spec or at least minimal reproducible sample? Does this issue happen with not-modified version of ReDoc?

**Comment by RomanGotsiy** [comment]
closing as stale
feel free to reopen
